version: '3.7'
services:
  web:
    build: .
    container_name: 'web_container'
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: 'db_container'
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'


  redis:
    image: redis
    restart: always
    container_name: 'redis_container'
    command: redis-server
    ports:
      - '6379:6379'

  celery:
    build: .
    container_name: 'celery_container'
    command: celery -A config worker --beat --scheduler django --loglevel=info
    env_file:
      - ./.env
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis
      - db

  flower:
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=redis://redis_container:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888

  chrome:
    image: selenium/standalone-chrome:4.0.0-beta-1-prerelease-20210106
    container_name: 'driver'
    volumes:
      - /dev/shm:/dev/shm
    restart: always
    ports:
      - "4444:4444"

volumes:
  postgres_data:

networks:
    common:
